# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make /app/data directory if it doesn't exist
RUN mkdir -p /app/data

# Ensure the script is executable
RUN chmod +x your_inference_script.py

# Set the entrypoint to run the inference script
ENTRYPOINT ["python", "./inference_script.py"]
